openapi: 3.0.0
info:
  title: SBC Pay API Reference
  description: BC Registries Pay API reference documentation
  version: 1.0.1
paths:
  '/api/v1/fees/{corp_type}/{filing_type_code}':
    get:
      tags:
        - Fees
      summary: Calculate Fees
      description: Calculate Fees on the filing type for corp type
      operationId: Calculate_Fees
      parameters:
        - name: corp_type
          in: path
          description: Corp Type
          required: true
          schema:
            type: string
        - name: filing_type_code
          in: path
          description: Filing type code
          required: true
          schema:
            type: string
        - name: jurisdiction
          in: query
          description: Jurisdiction or Province code
          required: false
          schema:
            type: string
        - name: date
          in: query
          description: Date on which the filing rates are applicable
          required: false
          schema:
            type: string
        - name: priority
          in: query
          description: Indicator if priority fees are applicable
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                OTANN:
                  value: 'application:prod'
                OTCDR:
                  value: 'application:prod'
                OTADD:
                  value: 'application:prod'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                OTANN:
                  value: '*'
                OTCDR:
                  value: '*'
                OTADD:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                OTANN:
                  value: 'GET, POST, DELETE, PUT'
                OTCDR:
                  value: 'GET, POST, DELETE, PUT'
                OTADD:
                  value: 'GET, POST, DELETE, PUT'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                OTANN:
                  value: 'Content-Type, api_key, Authorization'
                OTCDR:
                  value: 'Content-Type, api_key, Authorization'
                OTADD:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fee'
              examples:
                OTANN:
                  value:
                    filingType: Annual Report
                    filingTypeCode: OTANN
                    filingFees: 30
                    serviceFees: 0
                    processingFees: 0
                    tax:
                      gst: 0
                      pst: 0
                OTCDR:
                  value:
                    filingType: Change of Registered Office Address
                    filingTypeCode: OTCDR
                    filingFees: 20
                    serviceFees: 10
                    processingFees: 5
                    tax:
                      gst: 0
                      pst: 0
                OTADD:
                  value:
                    filingType: Change of Director
                    filingTypeCode: OTADD
                    filingFees: 55
                    serviceFees: 0
                    processingFees: 0
                    tax:
                      gst: 0
                      pst: 0
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - schema:
          type: string
        name: corp_type
        in: path
        required: true
      - schema:
          type: string
        name: filing_type_code
        in: path
        required: true
      - name: jurisdiction
        in: query
        required: true
        schema:
          type: string
        examples:
          fee_1:
            value: BC
      - name: date
        in: query
        schema:
          type: string
        examples:
          fee_1:
            value: '2018-12-31'
      - name: priority
        in: query
        schema:
          type: boolean
        examples:
          fee_1:
            value: false
  /api/v1/payment-requests:
    post:
      tags:
        - Payments
      summary: Create payment records
      description: Creates payment records.
      operationId: Create_Payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
            examples:
              payment_post_1:
                value:
                  paymentInfo:
                    methodOfPayment: CC
                  businessInfo:
                    businessIdentifier: CP1234567
                    corpType: CP
                    businessName: ABC Corp
                    contactInfo:
                      city: Victoria
                      postal_code: V8P2P2
                      province: BC
                      addressLine1: 100 Douglas Street
                      country: CA
                  filingInfo:
                    filingTypes:
                      - filingTypeCode: OTADD
                        filingDescription: TEST
                      - filingTypeCode: OTANN
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
              examples:
                payment_post_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests
                      invoices: /api/v1/payment-requests/153/invoices
                      self: /api/v1/payment-requests/153
                      transactions: /api/v1/payment-requests/153/transactions
                    createdBy: CP1234567
                    createdOn: '2019-06-18T11:10:00.965101+00:00'
                    id: 153
                    invoices:
                      - _links:
                          collection: /api/v1/payment-requests/153/invoices
                          self: /api/v1/payment-requests/153/invoices/152
                        createdBy: CP1234567
                        createdOn: '2019-06-18T11:10:00.982551+00:00'
                        id: 152
                        invoiceNumber: '10021'
                        paid: 0
                        paymentDate: null
                        referenceNumber: '10005'
                        refund: 0
                        statusCode: CREATED
                        total: 50
                        updatedBy: null
                        updatedOn: null
                    paid: 0
                    paymentMethod: CC
                    paymentSystem: PAYBC
                    statusCode: CREATED
                    updatedBy: null
                    updatedOn: null
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/api/v1/payment-requests/{payment_identifier}':
    put:
      tags:
        - Payments
      summary: Update payment records
      description: Updates payment records.
      operationId: Update_Payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
            examples:
              payment_1:
                value:
                  paymentInfo:
                    methodOfPayment: CC
                  businessInfo:
                    businessIdentifier: CP1234567
                    corpType: CP
                    businessName: ABC Corp
                    contactInfo:
                      city: Victoria
                      postalCode: V8P2P2
                      province: BC
                      addressLine1: 100 Douglas Street
                      country: CA
                  filingInfo:
                    filingTypes:
                      - filingTypeCode: OTADD
                        filingDescription: TEST
                      - filingTypeCode: OTANN
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
              examples:
                payment_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests
                      invoices: /api/v1/payment-requests/153/invoices
                      self: /api/v1/payment-requests/153
                      transactions: /api/v1/payment-requests/153/transactions
                    createdBy: CP1234567
                    createdOn: '2019-06-18T11:10:00.965101+00:00'
                    id: 153
                    invoices:
                      - _links:
                          collection: /api/v1/payment-requests/153/invoices
                          self: /api/v1/payment-requests/153/invoices/152
                        createdBy: CP1234567
                        createdOn: '2019-06-18T11:10:00.982551+00:00'
                        id: 152
                        invoiceNumber: '10021'
                        paid: 0
                        paymentDate: null
                        referenceNumber: '10005'
                        refund: 0
                        statusCode: CREATED
                        total: 50
                        updatedBy: null
                        updatedOn: null
                    paid: 0
                    paymentMethod: CC
                    paymentSystem: PAYBC
                    statusCode: CREATED
                    updatedBy: null
                    updatedOn: null
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - Payments
      summary: Get Payment
      description: Get Payment by filing identifier
      operationId: Get_Payment
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                payment_1:
                  value: 'application:prod'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                payment_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                payment_1:
                  value: 'GET, POST, DELETE, PUT'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                payment_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
              examples:
                payment_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests
                      invoices: /api/v1/payment-requests/153/invoices
                      self: /api/v1/payment-requests/153
                      transactions: /api/v1/payment-requests/153/transactions
                    createdBy: CP1234567
                    createdOn: '2019-06-18T11:10:00.965101+00:00'
                    id: 153
                    invoices:
                      - _links:
                          collection: /api/v1/payment-requests/153/invoices
                          self: /api/v1/payment-requests/153/invoices/152
                        createdBy: CP1234567
                        createdOn: '2019-06-18T11:10:00.982551+00:00'
                        id: 152
                        invoiceNumber: '10021'
                        referenceNumber: '10005'
                        statusCode: CREATED
                        total: 50
                        updatedBy: CP1234567
                        updatedOn: '2019-06-20T16:30:04.441211+00:00'
                    paymentMethod: CC
                    paymentSystem: PAYBC
                    statusCode: CREATED
                    updatedBy: CP1234567
                    updatedOn: '2019-06-20T16:30:04.451576+00:00'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - schema:
          type: string
        name: payment_identifier
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-api-v1-payment-requests-payment_identifier
      responses:
        '200':
          description: OK
      description: DELETE payment request
  '/api/v1/payment-requests/{payment_identifier}/transactions':
    post:
      tags:
        - Transactions
      summary: Create a transaction
      description: Creates a transaction for the payment.
      operationId: Create_Transaction
      parameters:
        - name: redirect_uri
          in: query
          description: Redirect URI
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
              examples:
                payment_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests/153/transactions
                      self: /api/v1/payment-requests/153/transactions/3378001e-cfd5-479b-84a2-bfd4e7eb804d
                    clientCystemUrl: 'http://localhost:8080/coops-web/transactions?transaction_id=abcd'
                    endTime: '2019-06-20 14:55:41.309606'
                    id: 3378001e-cfd5-479b-84a2-bfd4e7eb804d
                    paySystemUrl: 'http://localhost:8080/Payment?inv_number=10021&pbc_ref_number=10005&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Freturnpayment%2F153%2Ftransaction%2F3378001e-cfd5-479b-84a2-bfd4e7eb804d'
                    paymentId: 153
                    startTime: '2019-06-20 14:55:41.309574'
                    statusCode: CREATED
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - Transactions
      summary: Get Transactions
      description: Get Transactions for the payment
      operationId: Get_Transactions
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                payment_1:
                  value: 'application:prod'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                payment_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                payment_1:
                  value: 'GET, POST, DELETE, PUT'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                payment_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
              examples:
                payment_1:
                  value:
                    items:
                      - _links:
                          collection: /api/v1/payment-requests/153/transactions
                          self: /api/v1/payment-requests/153/transactions/3378001e-cfd5-479b-84a2-bfd4e7eb804d
                        clientSystemUrl: 'http://localhost:8080/coops-web/transactions?transaction_id=abcd'
                        endTime: '2019-06-20 14:55:41.309606'
                        id: 3378001e-cfd5-479b-84a2-bfd4e7eb804d
                        paySystemUrl: 'http://localhost:8080/Payment?inv_number=10021&pbc_ref_number=10005&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Freturnpayment%2F153%2Ftransaction%2F3378001e-cfd5-479b-84a2-bfd4e7eb804d'
                        paymentId: 153
                        startTime: '2019-06-20 14:55:41.309574'
                        statusCode: CREATED
                      - _links:
                          collection: /api/v1/payment-requests/153/transactions
                          self: /api/v1/payment-requests/153/transactions/227ea487-8f89-4897-849a-ae65febf91fe
                        clientSystemUrl: 'http://localhost:8080/coops-web/transactions?transaction_id=abcd'
                        endTime: '2019-06-20 16:32:15.271165'
                        id: 227ea487-8f89-4897-849a-ae65febf91fe
                        paySystemUrl: 'http://localhost:8080/Payment?inv_number=10021&pbc_ref_number=10005&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Freturnpayment%2F153%2Ftransaction%2F227ea487-8f89-4897-849a-ae65febf91fe'
                        paymentId: 153
                        startTime: '2019-06-20 14:55:41.309574'
                        statusCode: CANCELLED
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - schema:
          type: string
        name: payment_identifier
        in: path
        required: true
  '/api/v1/payment-requests/{payment_identifier}/transactions/{transaction_identifier}':
    put:
      tags:
        - Transactions
      summary: Update a transaction
      description: Updaate transaction for the payment.
      operationId: Update_Transaction
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
        - name: receipt_number
          in: query
          description: Receipt Number for the payment
          required: true
          schema:
            type: string
        - name: transaction_identifier
          in: path
          description: Unique Identifier for the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
              examples:
                payment_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests/153/transactions
                      self: /api/v1/payment-requests/153/transactions/3378001e-cfd5-479b-84a2-bfd4e7eb804d
                    clientSystemUrl: 'http://localhost:8080/coops-web/transactions?transaction_id=abcd'
                    endTime: '2019-06-20 14:55:41.309606'
                    id: 3378001e-cfd5-479b-84a2-bfd4e7eb804d
                    paySystemUrl: 'http://localhost:8080/Payment?inv_number=10021&pbc_ref_number=10005&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Freturnpayment%2F153%2Ftransaction%2F3378001e-cfd5-479b-84a2-bfd4e7eb804d'
                    paymentId: 153
                    startTime: '2019-06-20 14:55:41.309574'
                    statusCode: COMPLETED
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - Transactions
      summary: Get Transaction
      description: Get a Transaction for the payment
      operationId: Get_Transaction
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
        - name: transaction_identifier
          in: path
          description: Unique Identifier for the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                payment_1:
                  value: 'application:prod'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                payment_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                payment_1:
                  value: 'GET, POST, DELETE, PUT'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                payment_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
              examples:
                payment_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests/153/transactions
                      self: /api/v1/payment-requests/153/transactions/3378001e-cfd5-479b-84a2-bfd4e7eb804d
                    clientSystemUrl: 'http://localhost:8080/coops-web/transactions?transaction_id=abcd'
                    endTime: '2019-06-20 14:55:41.309606'
                    id: 3378001e-cfd5-479b-84a2-bfd4e7eb804d
                    paySystemUrl: 'http://localhost:8080/Payment?inv_number=10021&pbc_ref_number=10005&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Freturnpayment%2F153%2Ftransaction%2F3378001e-cfd5-479b-84a2-bfd4e7eb804d'
                    paymentId: 153
                    startTime: '2019-06-20 14:55:41.309574'
                    statusCode: CREATED
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - name: payment_identifier
        in: path
        required: true
        schema:
          format: string
          type: string
        examples:
          payment_1:
            value: 153
      - name: transaction_identifier
        in: path
        required: true
        schema:
          format: string
          type: string
        examples:
          payment_1:
            value: 3378001e-cfd5-479b-84a2-bfd4e7eb804d
      - name: receipt_number
        in: query
        description: Receipt Number for the payment
        required: true
        schema:
          type: string
        examples:
          payment_1:
            value: 'http%3A//localhost%3A8080/coops-web/transactions%3Ftransaction_id%3Dabcd'
  '/api/v1/payment-requests/{payment_identifier}/invoices':
    get:
      tags:
        - Invoices
      summary: Get Invoices
      description: Get Invoices for the payment
      operationId: Get_Invoices
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                payment_1:
                  value: 'application:prod'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                payment_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                payment_1:
                  value: 'GET, POST, DELETE, PUT'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                payment_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
              examples:
                payment_1:
                  value:
                    items:
                      - _links:
                          collection: /api/v1/payment-requests/153/invoices
                          self: /api/v1/payment-requests/153/invoices/152
                        createdBy: CP1234567
                        createdOn: '2019-06-18T11:10:00.982551+00:00'
                        id: 152
                        invoiceNumber: '10021'
                        lineItems:
                          - description: Change of Directors - Director A
                            filingFees: 20
                            gst: 0
                            id: 371
                            processingFees: 0
                            pst: 0
                            quantity: 1
                            serviceFees: 0
                            statusCode: CREATED
                            total: 20
                          - description: Annual Report
                            filingFees: 30
                            gst: 0
                            id: 372
                            processingFees: 0
                            pst: 0
                            quantity: 1
                            serviceFees: 0
                            statusCode: CREATED
                            total: 30
                        referenceNumber: '10005'
                        statusCode: CREATED
                        total: 50
                        updatedBy: CP1234567
                        updatedOn: '2019-06-20T16:30:04.441211+00:00'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - name: payment_identifier
        in: path
        required: true
        schema:
          format: string
          type: string
        examples:
          payment_1:
            value: 153
  '/api/v1/payment-requests/{payment_identifier}/invoices/{invoice_id}':
    get:
      tags:
        - Invoices
      summary: Get Invoice
      description: Get an invoice for the payment
      operationId: Get_Invoice
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
        - name: invoice_id
          in: path
          description: Unique Identifier for the invoice
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          headers:
            X-Application-Context:
              schema:
                type: string
              description: X-Application-Context
              examples:
                payment_1:
                  value: 'application:prod'
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Access-Control-Allow-Origin
              examples:
                payment_1:
                  value: '*'
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Access-Control-Allow-Methods
              examples:
                payment_1:
                  value: 'GET, POST, DELETE, PUT'
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Access-Control-Allow-Headers
              examples:
                payment_1:
                  value: 'Content-Type, api_key, Authorization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
              examples:
                payment_1:
                  value:
                    _links:
                      collection: /api/v1/payment-requests/153/invoices
                      self: /api/v1/payment-requests/153/invoices/152
                    createdBy: CP1234567
                    createdOn: '2019-06-18T11:10:00.982551+00:00'
                    id: 152
                    invoiceNumber: '10021'
                    lineItems:
                      - description: Change of Directors - Director A
                        filingFees: 20
                        gst: 0
                        id: 371
                        processingFees: 0
                        pst: 0
                        quantity: 1
                        serviceFees: 0
                        statusCode: CREATED
                        total: 20
                      - description: Annual Report
                        filingFees: 30
                        gst: 0
                        id: 372
                        processingFees: 0
                        pst: 0
                        quantity: 1
                        serviceFees: 0
                        statusCode: CREATED
                        total: 30
                    referenceNumber: '10005'
                    statusCode: CREATED
                    total: 50
                    updatedBy: CP1234567
                    updatedOn: '2019-06-20T16:30:04.441211+00:00'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - name: payment_identifier
        in: path
        required: true
        schema:
          format: string
          type: string
        examples:
          payment_1:
            value: 153
      - name: invoice_id
        in: path
        required: true
        schema:
          format: string
          type: string
        examples:
          payment_1:
            value: 152
  '/api/v1/payment-requests/{payment_identifier}/receipts':
    get:
      tags:
        - Receipts
      summary: Get receipt for the payment
      description: Returns payment receipt details
      operationId: Get_Receipt
      parameters:
        - name: payment_identifier
          in: path
          description: Unique Identifier for the payment
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Receipt PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - schema:
          type: string
        name: payment_identifier
        in: path
        required: true
  /api/v1/accounts:
    post:
      tags:
        - Accounts
      summary: Create Payment Account records
      description: Create Payment Account records.
      operationId: Create_Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInfo'
            examples:
              account:
                value:
                  accountId: 1
                  accountName: test_account_name
                  paymentInfo:
                    methodOfPayment: CC
                    billable: true
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                account:
                  value:
                    authAccountId: 1
                    authAccountName: tester
                    bcolAccount:
                    bcolUserId:
                    billable: true
                    credit:
                    id: 64
                    runningBalance:
                    statementNotificationEnabled: false
                    versions:
                      - id: 64
                        transactionId: 115
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/api/v1/accounts/{org_id}':
    put:
      tags:
        - Accounts
      summary: Update payment Account records
      description: Updates payment Account records.
      operationId: Update_Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInfo'
            examples:
              account_info_1:
                value:
                  accountId: 1
                  accountName: test_account_name
                  paymentInfo:
                    methodOfPayment: CC
                    billable: true
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                account_post_1:
                  value:
                    authAccountId: '19'
                    authAccountName: tester
                    bcolAccount:
                    bcolUserId:
                    billable: true
                    credit:
                    id: 64
                    runningBalance:
                    statementNotificationEnabled: false
                    versions:
                      - id: 64
                        transactionId: 115
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    parameters:
      - schema:
          type: string
        name: org_id
        in: path
        required: true

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Identifier representing the type of error that occurred.
        message:
          type: string
          description: Description of the error.
      description: Contains details of an error that was encountered.
    Tax:
      type: object
      properties:
        gst:
          type: integer
          description: Good Services Tax
        pst:
          type: integer
          description: Provincial Sales Tax
    Fee:
      type: object
      properties:
        filingTypeCode:
          type: string
          description: Filing Type Code
        filingType:
          type: string
          description: Filing Type
        filingFees:
          type: integer
          description: Fees for filing
        serviceFees:
          type: integer
          description: Applicable service fees
        processingFees:
          type: integer
          description: Applicable processing fees
        tax:
          type: object
          items:
            $ref: '#/components/schemas/Tax'
    PaymentLineItem:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for payment line item
        invoiceId:
          type: integer
          description: Unique identifier for invoice
        feeScheduleId:
          type: integer
          description: Fee schedule id
        quantity:
          type: integer
          description: Quantity of fee
        filingFees:
          type: number
          description: Fees for filing
        serviceFees:
          type: number
          description: Applicable service fees
        processingFees:
          type: number
          description: Applicable processing fees
        description:
          type: number
          description: Description of the fee item
        gst:
          type: number
          description: Applicable gst of the fee item
        pst:
          type: number
          description: Applicable pst of the fee item
        statusCode:
          type: string
          description: Line item status
          enum:
            - DRAFT
            - IN_PROGRESS
            - CREATED
            - COMPLETED
            - PARTIAL
            - FAILED
            - REFUNDED
            - CANCELLED
    PaymentRequest:
      type: object
      properties:
        paymentInfo:
          type: object
          items:
            $ref: '#/components/schemas/PaymentInfo'
        filingInfo:
          type: object
          items:
            $ref: '#/components/schemas/FilingInfo'
        businessInfo:
          type: object
          items:
            $ref: '#/components/schemas/BusinessInfo'
    PaymentInfo:
      type: object
      properties:
        methodOfPayment:
          type: string
          description: Method of payment
    FilingInfo:
      type: object
      properties:
        corp_type:
          type: string
          description: Corp Type
        date:
          type: string
          description: Date on which the filing rates are applicable
        filingTypes:
          type: array
          items:
            $ref: '#/components/schemas/FilingType'
    FilingType:
      type: object
      properties:
        filingTypeCode:
          type: string
          description: Filing Type Code
        priority:
          type: boolean
          description: Priority Indicator
        filingDescription:
          type: string
          description: Filing Type Description
    BusinessInfo:
      type: object
      properties:
        businessIdentifier:
          type: string
          description: Business identifier
        businessName:
          type: string
          description: Legal entity name
        contactInfo:
          type: object
          items:
            $ref: '#/components/schemas/ContactInfo'
    ContactInfo:
      type: object
      properties:
        firstName:
          type: string
          description: Contact first name
        lastName:
          type: string
          description: Contact last name
        address:
          type: string
          description: Addres line 1
        city:
          type: string
          description: City
        province:
          type: string
          description: Province
        postalCode:
          type: string
          description: Postal Code
    Payment:
      type: object
      properties:
        _links:
          type: object
          items:
            $ref: '#/components/schemas/Links'
        id:
          type: integer
          description: Unique identifier for payment
        createdBy:
          type: string
          description: username of the account
        createdOn:
          type: string
          description: payment creation date
        invoices:
          type: array
          items:
            $ref: '#/components/schemas/Invoice'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        paymentMethod:
          type: string
          description: code of payment method
        statusCode:
          type: string
          description: Status of payment.
          enum:
            - DRAFT
            - IN_PROGRESS
            - CREATED
            - COMPLETED
            - PARTIAL
            - FAILED
            - REFUNDED
            - CANCELLED
        updatedBy:
          type: string
          description: username of the account that made update
        updatedOn:
          type: string
          description: payment update date
    Invoice:
      type: object
      properties:
        _links:
          type: object
          items:
            $ref: '#/components/schemas/Links'
        id:
          type: integer
          description: Unique identifier for invoice
        accountId:
          type: integer
          description: id of the account
        createdBy:
          type: string
          description: username of the account
        createdOn:
          type: string
          description: invoice creation date
        paymentDate:
          type: string
          description: date made payment
        paymentId:
          type: integer
          description: payment identifier
        paid:
          type: number
          description: amount paid
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/PaymentLineItem'
        referenceNumber:
          type: string
          description: reference number
        statusCode:
          type: string
          description: Status of payment.
          enum:
            - DRAFT
            - IN_PROGRESS
            - CREATED
            - COMPLETED
            - PARTIAL
            - FAILED
            - REFUNDED
            - CANCELLED
    Invoices:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Invoice'
    Transaction:
      type: object
      properties:
        _links:
          type: object
          items:
            $ref: '#/components/schemas/Links'
        id:
          type: string
          description: Unique identifier for transaction
        clientSystemUrl:
          type: string
          description: Client system url
        startTime:
          type: string
          description: transaction start time
        endTime:
          type: string
          description: transaction end time
        paySystemUrl:
          type: string
          description: Payment system url
        paymentId:
          type: integer
          description: id of the payment
        statusCode:
          type: string
          description: Status of payment.
          enum:
            - DRAFT
            - IN_PROGRESS
            - CREATED
            - COMPLETED
            - PARTIAL
            - FAILED
            - REFUNDED
            - CANCELLED
    Transactions:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Links:
      type: object
      properties:
        self:
          type: string
          description: Self link
        collection:
          type: string
          description: collection link
    AccountInfo:
      type: object
      properties:
        accountId:
          type: integer
          description: Account Id
        accountName:
          type: string
          description: Name of Account
        paymentInfo:
          type: object
          properties:
            methodOfPayment:
              type: string
              description: method of payment as CC
            billable:
              type: boolean
              description: is it billable
